
CREATE TABLE [User] (
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	Connection NVARCHAR(50) NOT NULL,
	Username NVARCHAR (50) NOT NULL,
	Fullname NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL, 
	TimeStampIns DATETIME NOT NULL DEFAULT GETDATE(),
	TimeStampUpd DATETIME 
);	


SELECT * FROM [User];

SELECT @@SERVERNAME